image: maven:latest
cache:
    paths:
    - ~/.m2/
jar:
    script: 
    - wget 'https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar' -O BuildTools.jar
    - java -jar BuildTools.jar --rev 1.8.8
    artifacts:
        paths:
        - target/*.jar
    only:
    - master